name: Dapp Tests

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

jobs:
  setup-local-hedera:
    name: Dapp Tests
    runs-on: ubuntu-latest
    timeout-minutes: 35
    permissions:
      contents: write
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: |
          cp ./packages/server/tests/localDappCI.env ./dapp-example/.env
          cp ./packages/server/tests/localAcceptance.env .env

      - name: Lerna Bootstrap
        run: npm run setup

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript
        run: npx lerna run build

      - name: Run RPC Server
        run: npm run integration:prerequisite &

      - name: Check local node
        run: npm run check:node

      - name: Build, Bootstrap & Test the dapp in Docker
        run: docker-compose up --exit-code-from synpress
        working-directory: ./dapp-example/

      - name: Publish Reports
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          github_token: ${{ github.token }}
          check_name: Dapp Test Report
          report_paths: "**/*.xml"
          detailed_summary: true
          include_passed: true
